<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="block <?= $block->escapeHtmlAttr($block->getBlockCss()) ?>">
    <div class="title <?= $block->escapeHtmlAttr($block->getBlockCss()) ?>-title"
         data-mage-init='{"toggleAdvanced": {"toggleContainers": "#<?= $block->escapeHtmlAttr($block->getBlockCss()) ?>", "selectorsToggleClass": "active"}}'>
        <h3 class="title"><?php /* @escapeNotVerified */ echo __('Account Navigation');  ?></h3>
    </div>
    <div class="content <?= $block->escapeHtmlAttr($block->getBlockCss()) ?>-content"
         id="<?= $block->escapeHtmlAttr($block->getBlockCss()) ?>">
        <?= $block->getChildHtml() ?>
    </div>
</div>
