<?php
/**
 * Copyright © Aventi SAS All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<script>
    require([
        'jquery'
    ], function ($) {
        $citydropdownCityGet = '<?= /** @noEscape */ $block->getUrl('citydropdown/city/get')?>';
    });
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Aventi_CityDropDown/js/city-customer-edit": {}
        }
    }
</script>
