<?php
$controller = $block->getCustomUrl();
echo $block->getButtonHtml();
?>

<script type="text/javascript">
    let country= "us";
    let sistecredito_gateway_validate_field="sistecredito_gateway_validate_field"
    let sistecredito_gateway_validate_field_error="sistecredito_gateway_validate_field-error"
    let sistecredito_gateway_vendor_id="sistecredito_gateway_vendor_id"
    let sistecredito_gateway_store_id="sistecredito_gateway_store_id"
    let sistecredito_gateway_subscription_key="sistecredito_gateway_subscription_key"
    let sistecredito_gateway_environment="sistecredito_gateway_environment"

    if(document.getElementById(`payment_${country}_${sistecredito_gateway_vendor_id}`)===null){
        country="other"
    }

    sistecredito_gateway_validate_field = `payment_${country}_${sistecredito_gateway_validate_field}`;
    sistecredito_gateway_validate_field_error = `payment_${country}_${sistecredito_gateway_validate_field_error}`;
    sistecredito_gateway_vendor_id = `payment_${country}_${sistecredito_gateway_vendor_id}`;
    sistecredito_gateway_store_id = `payment_${country}_${sistecredito_gateway_store_id}`;
    sistecredito_gateway_subscription_key = `payment_${country}_${sistecredito_gateway_subscription_key}`;
    sistecredito_gateway_environment = `payment_${country}_${sistecredito_gateway_environment}`;

    const setValidationField = () => {
        const validate_field = document.getElementById(
            sistecredito_gateway_validate_field
        );
        validate_field.value = null;
    };


    const displayAlert = (title, content, modalClass = "alert_accept", Image = null, buttonText = 'Aceptar', buttonClass = "action_accept") => {
        require(["jquery", "Magento_Ui/js/modal/alert"], function($, alert) {

            alert({
                title: title,
                image: Image,
                modalClass: modalClass,
                content: content,
                buttons: [{
                    text: buttonText,
                    class: buttonClass,
                    click: function() {
                        this.closeModal(true);
                    }
                }]
            });
        });
        return;
    }

    const vendorIdListener = document.getElementById('save');
    vendorIdListener.addEventListener('click', (event) => {
        const validate_field = document.getElementById(
            sistecredito_gateway_validate_field
        );
        const validate_field_error = document.getElementById(
            sistecredito_gateway_validate_field_error
        );

        if (!validate_field.value) {
            var title = 'Realizar validación';
            var content = "click en Validate Credentials";
            displayAlert(title, content);
        }

    });

    const vendorListener = document.getElementById(sistecredito_gateway_vendor_id);
    vendorListener.addEventListener('change', (event) => {
        setValidationField();
    });

    const storeIdListener = document.getElementById(sistecredito_gateway_store_id);
    storeIdListener.addEventListener('change', (event) => {
        setValidationField();
    });

    const subcriptionKeyListener = document.getElementById(sistecredito_gateway_subscription_key);
    subcriptionKeyListener.addEventListener('change', (event) => {
        setValidationField();
    });

    require(["jquery", "Magento_Ui/js/modal/alert"], function($, alert) {
        $("#btn_validation_keys").on("click", async function(event) {
            const validate_field = document.getElementById(
                sistecredito_gateway_validate_field
            );
            const vendor_id = document.getElementById(
                sistecredito_gateway_vendor_id
            );
            const store_id = document.getElementById(
                sistecredito_gateway_store_id
            );
            const subscription_key = document.getElementById(
                sistecredito_gateway_subscription_key
            );

            const environment = document.getElementById(
                sistecredito_gateway_environment
            ).value;
            const scLocation = "0,0";
            const country = "co";
            let scOrigen = "";
            let environmentService = "";
            switch (environment) {
                case "Development":
                    scOrigen = "Development";
                    environmentService =
                        "https://api-co-nop-internal.sistecreditocloud.com/vendors/GetStoreVendorByIds?";
                    break;
                case "Qa":
                    scOrigen = "Qa";
                    environmentService =
                        "https://api-co-nop-internal.sistecreditocloud.com/vendors/GetStoreVendorByIds?";
                    break;
                case "Staging":
                    scOrigen = "Staging";
                    environmentService =
                        "https://api-co-stg.sistecreditocloud.com/vendors/GetStoreVendorByIds?";
                    break;
                case "Production":
                    scOrigen = "Production";
                    environmentService =
                        "https://api.sistecredito.com/vendors/GetStoreVendorByIds?";
                    break;
            }
            const options = {
                method: "GET",
                headers: {
                    SCLocation: scLocation,
                    SCOrigen: scOrigen,
                    country: country,
                    "Content-Type": "application/json",
                    "Ocp-Apim-Subscription-Key": subscription_key.value,
                },
            };
            await fetch(
                    environmentService +
                    new URLSearchParams({
                        storeId: store_id.value,
                        vendorId: vendor_id.value,
                    }).toString(),
                    options
                )
                .then((response) => response.text())
                .then((data) => {
                    const res = JSON.parse(data);
                    if (res.errorCode !== 0) {
                        validate_field.value = null;
                        vendor_id.classList.add("error-keys");
                        store_id.classList.add("error-keys");
                        subscription_key.classList.add("error-keys");

                        const title = "<p></p>";
                        const modalClass = 'alert_accept';
                        const content = "Los campos resaltados pueden tener información incorrecta, por favor verifica e inténtalo nuevamente";

                        displayAlert(title, content, modalClass);

                        return
                    } else {
                        validate_field.value = true;
                        vendor_id.classList.remove("error-keys");
                        store_id.classList.remove("error-keys");
                        subscription_key.classList.remove("error-keys");

                        const title = "<div><img></div> ¡Bien Hecho!";
                        const modalClass = 'alert_continue';
                        const content = "Todos los campos están correctos";
                        const buttontext = "Continuar";

                        displayAlert(title, content, modalClass, null, buttontext);

                        return
                    }
                })
                .catch((error) => {
                    return error;
                });
        });
    });
</script>
