<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php
$themeSettingConfig = $this->helper('MGS\ThemeSettings\Helper\Config');
$class = "";
$logoMobile = $themeSettingConfig->getStoreConfig('themesettings/header/mobile_logo');
if($logoMobile){
	$class .= " exits-lg-mb";
}
$stickyMobile = $themeSettingConfig->getStoreConfig('themesettings/header/sticky_logo');
if($stickyMobile){
	$class .= " exits-lg-stk";
}
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
    <div id="home-logo-go" class="cursor-pinter logo<?= $class ?>" href="<?= $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>">
        <img class="default-logo" src="<?php /* @escapeNotVerified */ echo $block->getLogoSrc() ?>"
             alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
             <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
             <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
        />
		<?php if($logoMobile): ?>
			<img class="mobile-logo" src="<?php /* @escapeNotVerified */ echo $themeSettingConfig->getMediaUrl('mgs/setting/' . $logoMobile) ?>"
             alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"/>
		<?php endif ?>
		<?php if($stickyMobile): ?>
			<img class="sticky-logo" src="<?php /* @escapeNotVerified */ echo $themeSettingConfig->getMediaUrl('mgs/setting/' . $stickyMobile) ?>"
             alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"/>
		<?php endif ?>
        </div>
<script>
    require([
    'jquery',
    'mage/cookies'
    ], function ($) {
        $('#home-logo-go').on('click', function(){
           const href = $(this).attr('href');
           const locateCurrent = window.location.href;
           const check = $.cookie('prehomecookie');

           if (locateCurrent !== href) {
               $.cookie('prehomecookie', null);
               window.location.href = href;
           }
        });
    });
</script>