<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Button $block */
?>
<?php if ($block->getWishlist()->getItemsCount() && $block->getWishlist()->getShared() < $block->getConfig()->getSharingEmailLimit()) : ?>
    <div class="col-des-4 col-tb-4 col-mb-12">
        <button type="submit" name="save_and_share" title="<?= $block->escapeHtmlAttr(__('Share Wish List')) ?>" class="action share btn btn-secondary btn-square btn-full">
            <span><?= $block->escapeHtml(__('Share Wish List')) ?></span>
        </button>
    </div>
<?php endif;?>
