<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Button $block */
?>

<?php if ($block->getWishlist()->getItemsCount() && $block->getWishlist()->isSalable()) : ?>
<div class="col-des-4 col-tb-4 col-mb-12">
    <button type="button" data-role="all-tocart" title="<?= $block->escapeHtmlAttr(__('Add All to Cart')) ?>" class="action tocart btn-primary btn-square btn btn-full">
        <span><?= $block->escapeHtml(__('Add All to Cart')) ?></span>
    </button>
</div>
<?php endif;?>
