<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Button $block */
?>

<?php if ($block->getWishlist()->getItemsCount()) : ?>
<div class="col-des-4 col-tb-4 col-mb-12">
    <button type="submit" name="do" title="<?= $block->escapeHtmlAttr(__('Update Wish List')) ?>" class="action update btn btn-default btn-square btn-full">
        <span><?= $block->escapeHtml(__('Update Wish List')) ?></span>
    </button>
</div>
<?php endif;?>
