<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>

<div class="login-form logged-customer">
    <button class="close-myaccount"><span class="icon-cross2"></span></button>
    <?php echo $block->getChildHtml('top.link.header'); ?>
</div>
