<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/**
 * @var \Magento\Checkout\Block\Cart\Grid $block
 * @var \Magento\Framework\Escaper $escaper
 */

$viewModel = $block->getData('viewModelForm');
?>
<?php $mergedCells = ($viewModel->getTaxHelperData()->displayCartBothPrices() ? 2 : 1); ?>
<?= $block->getChildHtml('form_before') ?>
<form action="<?= $escaper->escapeUrl($block->getUrl('checkout/cart/updatePost')) ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"Magento_Checkout/js/action/update-shopping-cart":
              {"validationURL" : "<?= $escaper->escapeUrl($block->getUrl('checkout/cart/updateItemQty')) ?>",
              "updateCartActionContainer": "#update_cart_action_container"}
          }'
          class="form form-cart">
    <?= $block->getBlockHtml('formkey') ?>
    <div class="cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-top toolbar"
                 data-attribute="cart-products-toolbar-top"><?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
        <table id="shopping-cart-table"
               class="cart items data table"
               data-mage-init='{"shoppingCart":{"emptyCartButton": ".action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
            <caption class="table-caption"><?= $escaper->escapeHtml(__('Shopping Cart Items')) ?></caption>
            <thead>
                <tr>
                    <th class="col item" scope="col"><span><?= $escaper->escapeHtml(__('Product')) ?></span></th>
                    <th class="col price" scope="col"><span><?= $escaper->escapeHtml(__('Price')) ?></span></th>
                    <th class="col discount" scope="col"><span><?= $escaper->escapeHtml(__('Discount')) ?></span></th>
                    <th class="col qty" scope="col"><span><?= $escaper->escapeHtml(__('Quantity')) ?></span></th>
                    <th class="col subtotal" scope="col"><span><?= $escaper->escapeHtml(__('Subtotal')) ?></span></th>
                </tr>
            </thead>
            <?php foreach ($block->getItems() as $_item): ?>
                <?= $block->getItemHtml($_item) ?>
            <?php endforeach ?>
        </table>
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar"
                 data-attribute="cart-products-toolbar-bottom"><?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
    </div>
    <div class="cart main actions">

        <?php if ($block->getViewModel()->isClearShoppingCartEnabled()): ?>
            <button type="button"
                    name="update_cart_action"
                    data-cart-empty=""
                    value="empty_cart"
                    title="<?= $escaper->escapeHtml(__('Clear Shopping Cart')) ?>"
                    class="action clear btn btn-primary" id="empty_cart_button">
                <span><?= $escaper->escapeHtml(__('Clear Shopping Cart')) ?></span>
            </button>
        <?php endif ?>
        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?= $escaper->escapeHtml(__('Update Shopping Cart')) ?>"
                class="action btn-update btn btn-default">
            <span><?= $escaper->escapeHtml(__('Update Shopping Cart')) ?></span>
        </button>
        <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
    </div>
</form>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>

<script>
    require([
        'jquery'
    ], function($) {
        /* Shipping & Discount Code */
        $('.checkout-extra > .block > .title').on('click', function() {
            $('.checkout-extra .block').removeClass('active');
            $('.checkout-extra .block .title').removeClass('active');
            $('.checkout-extra .block .content').removeClass('active');
            $(this).addClass('active');
            $(this).parent().find('> .content').addClass('active');
        });

        const handler = "#shopping-cart-table";

        $(handler).on("click", ".plus", function(e) {
            const qtyInput = e.target.previousElementSibling;
            const qtyInputId = e.target.previousElementSibling.id;
            let realQty<?php echo $_item->getId() ?> = parseInt(qtyInput.value);

            if($('#'+qtyInputId).attr('disabled') !== 'disabled'){
                realQty<?php echo $_item->getId() ?>++;
                $('#'+qtyInputId).val(realQty<?php echo $_item->getId() ?>);
            }
        });

        $(handler).on("click", ".minus", function(e) {
            const qtyInput = e.target.nextElementSibling;
            const qtyInputId = e.target.nextElementSibling.id;
            let realQty<?php echo $_item->getId() ?> = parseInt(qtyInput.value);

            if($('#'+qtyInputId).attr('disabled') !== 'disabled'){
                if(realQty<?php echo $_item->getId() ?> > 1){
                    realQty<?php echo $_item->getId() ?>--;
                    $('#'+qtyInputId).val(realQty<?php echo $_item->getId() ?>);
                }
            }
        });
    });
</script>
