<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<form class="form password forget"
      action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field note required">
            <label class="label">
                <?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?>
            </label>
        </div>
        <div class="field email required">
            <div class="control">
                <input type="email" placeholder="<?= $block->escapeHtml(__('Enter your email...')) ?>" name="email" alt="email" id="email_address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>
    </fieldset>
    <div class="actions-toolbar-form">
        <div class="line">
            <div class="col-des-6 col-tb-6 col-mb-12 margin-top15">
                <a class="action back btn btn-default btn-full" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
            </div>
            <div class="col-des-6 col-tb-6 col-mb-12 margin-top15">
                <button type="submit" class="action submit btn btn-primary btn-full"><span><?= $block->escapeHtml(__('Reset My Password')) ?></span></button>
            </div>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "form-validate"
            }
        }
    }
</script>
