<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Newsletter $block */
?>
<?= $block->getChildHtml('form_before') ?>
    <div class="block-title-account"><h3><?= $block->escapeHtml(__('Subscription option')) ?></h3></div>
    <form class="form form-newsletter-manage" action="<?= $block->escapeUrl($block->getAction()) ?>" method="post" id="form-validate">
        <fieldset class="fieldset">
            <?= $block->getBlockHtml('formkey') ?>
            <div class="field choice">
                <input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?= $block->escapeHtmlAttr(__('General Subscription')) ?>"<?php if ($block->getIsSubscribed()) : ?> checked="checked"<?php endif; ?> class="checkbox">
                <label for="subscription" class="label"><span><?= $block->escapeHtml(__('General Subscription')) ?></span></label>
            </div>
            <?php /* Extensions placeholder */ ?>
            <?= $block->getChildHtml('customer.form.newsletter.extra') ?>
        </fieldset>
        <div class="actions-toolbar-form">
            <div class="primary">
                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Save')) ?>" class="action save btn btn-primary btn-square"><span><?= $block->escapeHtml(__('Save')) ?></span></button>
                <a class="action btn btn-secondary btn-sm back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
            </div>
        </div>
    </form>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.newsletter.extra2') ?>
